### ISSUE TITLE
PuppetDB check is kind of useless

### ISSUE THREAD

**Issue by Fodoj** [flypenguin/puppet-openshiftinstaller#4]
Why this is needed at all? https://github.com/flypenguin/puppet-openshiftinstaller/blob/master/files/osi_puppetdb_running.py 

Every node doesnt have any issue contacting puppetdb on puppetmaster, by using puppetdb-query plugin. So this check only makes it impossible to use openshiftinstaller outside of puppetmaster without any particular reason :) 

Or may be I am missing something :)

**Comment by flypenguin** [comment]
sorry for the late response. no you are not missing something. The problem was that on the initial deployment of this module it was intended to be run from the puppet master, with an installed puppetdb. I think I remember that the system would actually break (and not "converge" by itself to a useful state) when it ran out of order, so I designed this crappy fact. 

it would be awesome if the fact could be rewritten so that it checks the presence of puppetdb in a more generic way, or that another could be introduced. *I* would not even care if that thing is removed, for I personally don't use it right now, but other people might. if you have successfully tested the module with a setup like described above, without this fact, then I also think there's no more reason for this.

**Comment by Fodoj** [comment]
Yeah, I tested it without the fact at all, works fine :)

**Comment by flypenguin** [comment]
Is a PR coming? :)

**Comment by Fodoj** [comment]
@flypenguin PR is here since months https://github.com/flypenguin/puppet-openshiftinstaller/pull/5

**Comment by flypenguin** [comment]
oh, right :) . my bad. merged.
